import fs from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import { createHash } from 'node:crypto'

const [inputPath, outputPath] = process.argv.slice(2)
if (!inputPath || !outputPath) {
  throw new Error('usage: node scripts/generateUnicodeCaseFold.mjs CaseFolding.txt output.ts')
}

const UNICODE_VERSION = '16.0.0'
const OFFICIAL_SOURCE_SHA256 = '6f1f9c588eb4a5c718d9e8f93b782685e5c7fec872cf05e8e6878053599e09bb'
const EXPECTED_DEFAULT_MAPPING_COUNT = 1557
const DATA_LINE = /^([0-9A-F]{4,6});\s*([CFST]);\s*([0-9A-F]{4,6}(?: [0-9A-F]{4,6})*);\s*#/
const sha256 = (value) => createHash('sha256').update(value).digest('hex')

const parseSource = (source, expectedHash = OFFICIAL_SOURCE_SHA256) => {
  if (sha256(source) !== expectedHash) throw new Error('CaseFolding source SHA-256 mismatch')
  const version = source.match(/^# CaseFolding-([0-9.]+)\.txt$/m)?.[1]
  if (version !== UNICODE_VERSION) throw new Error('CaseFolding data version mismatch')

  const mappings = []
  const seen = new Set()
  for (const rawLine of source.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue
    const match = line.match(DATA_LINE)
    if (!match) throw new Error('Malformed CaseFolding data line')
    if (match[2] !== 'C' && match[2] !== 'F') continue
    const from = Number.parseInt(match[1], 16)
    const to = match[3].split(' ').map((value) => Number.parseInt(value, 16))
    if (
      seen.has(from) ||
      from > 0x10ffff ||
      (from >= 0xd800 && from <= 0xdfff) ||
      to.some((codePoint) => codePoint > 0x10ffff || (codePoint >= 0xd800 && codePoint <= 0xdfff))
    ) {
      throw new Error('Invalid or duplicate CaseFolding mapping')
    }
    seen.add(from)
    mappings.push([from, to])
  }
  if (mappings.length !== EXPECTED_DEFAULT_MAPPING_COUNT) {
    throw new Error('Unexpected CaseFolding mapping count')
  }
  mappings.sort((left, right) => left[0] - right[0])
  return mappings
}

const source = await fs.readFile(inputPath, 'utf8')
const mappings = parseSource(source)

if (outputPath === '--self-test') {
  const expectFailure = (candidate, expectedMessage, expectedHash) => {
    try {
      parseSource(candidate, expectedHash)
    } catch (error) {
      if (error instanceof Error && error.message === expectedMessage) return
      throw error
    }
    throw new Error(`Self-test did not reject: ${expectedMessage}`)
  }
  expectFailure(`${source} `, 'CaseFolding source SHA-256 mismatch')
  const wrongVersion = source.replace('CaseFolding-16.0.0.txt', 'CaseFolding-99.0.0.txt')
  expectFailure(wrongVersion, 'CaseFolding data version mismatch', sha256(wrongVersion))
  const malformed = source.replace('0041; C;', '0041; X;')
  expectFailure(malformed, 'Malformed CaseFolding data line', sha256(malformed))
  const duplicate = `${source}\n0041; C; 0061; # duplicate\n`
  expectFailure(duplicate, 'Invalid or duplicate CaseFolding mapping', sha256(duplicate))
  process.stdout.write('UNICODE_CASE_FOLD_GENERATOR_SELF_TEST_PASS\n')
  process.exit(0)
}

const encoded = mappings
  .map(
    ([from, to]) =>
      `${from.toString(16).toUpperCase()}:${to
        .map((codePoint) => codePoint.toString(16).toUpperCase())
        .join('.')}`
  )
  .join(',')

const generated = `/**
 * Generated by scripts/generateUnicodeCaseFold.mjs from Unicode
 * CaseFolding-${UNICODE_VERSION}.txt using only C (common) and F (full) mappings.
 * T (Turkic) and S (simple alternatives to F) are intentionally excluded.
 * Source: https://www.unicode.org/Public/${UNICODE_VERSION}/ucd/CaseFolding.txt
 * Source SHA-256: ${OFFICIAL_SOURCE_SHA256}
 * Do not edit by hand.
 */

export const UNICODE_CASE_FOLD_VERSION = '${UNICODE_VERSION}'
const ENCODED_DEFAULT_CASE_FOLD = '${encoded}'

const DEFAULT_CASE_FOLD = new Map<number, string>(
  ENCODED_DEFAULT_CASE_FOLD.split(',').map((entry) => {
    const [source, encodedTarget] = entry.split(':')
    return [
      Number.parseInt(source, 16),
      String.fromCodePoint(
        ...encodedTarget.split('.').map((codePoint) => Number.parseInt(codePoint, 16))
      )
    ]
  })
)

/**
 * Locale-independent full Unicode Default Case Folding after NFC.
 *
 * Returns null for an ill-formed UTF-16 input so callers can fail closed.
 */
export const unicodeDefaultCaseFold = (value: string): string | null => {
  let result = ''
  for (const character of value.normalize('NFC')) {
    const codePoint = character.codePointAt(0)
    if (
      codePoint === undefined ||
      (codePoint >= 0xd800 && codePoint <= 0xdfff)
    ) {
      return null
    }
    result += DEFAULT_CASE_FOLD.get(codePoint) ?? character
  }
  return result
}
`

await fs.mkdir(path.dirname(outputPath), { recursive: true })
await fs.writeFile(outputPath, generated, 'utf8')
